apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.host }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      restartPolicy: Always
      containers:
        # v8 required extra libraries to be installed in airflow images for authentication
        - image: postgres:15
          name: postgres-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
